další verze

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -67,69 +67,53 @@ jobs:
             sleep 2
           done
 
-      - name: SSH prepare
+      - name: SSH deployment a testy
         shell: bash
         run: |
-          echo "Použitá větev: ${{ github.ref_name }}"
-
-          # Spustit SSH agenta
+          TEST_MOD="${{ inputs.test_mod }}"
+          NASADIT="${{ inputs.nasadit_verzi }}"
+          REF_NAME="${{ github.ref_name }}"
+          echo "Použitá větev: $REF_NAME"
           eval $(ssh-agent -s)
-
-          # Načíst privátní klíč
           echo "${{ secrets.SSH_PRIVATE_KEY_SERVER_DEV }}" | tr -d '\r' | ssh-add -
-
-          # Připravit ~/.ssh
           mkdir -p ~/.ssh
           chmod 700 ~/.ssh
           echo "${{ secrets.SSH_KNOWN_HOST_DEV }}" >> ~/.ssh/known_hosts
           chmod 644 ~/.ssh/known_hosts
+          sleep 2          
+          ping -c 5 ${{ secrets.DEPLOYMENT_SERVER_DEV }}          
+          echo "date_stamp=$(date +%Y%m%dT%H%M%S)" >> "$GITHUB_ENV"
+          ssh amcr@${{ secrets.DEPLOYMENT_SERVER_DEV }} << EOF
+          sudo su - root << AOF
+          cd ${{ env.server_deploy_root }}
+          chmod +x ${{ env.dep_script }}
+          chmod +x ${{ env.test_script }}
 
-          # Otestovat dostupnost serveru
-          ping -c 5 ${{ secrets.DEPLOYMENT_SERVER_DEV }}
+          if [ "$NASADIT" == "true" ]; then
+          echo "Nasazuji verzi: $REF_NAME"
+          ./${{ env.dep_script }} ${{ env.server_deploy_root }} $REF_NAME
+          fi
 
-      - name: Deployment + Testovani
-        shell: bash
-        run: |
-          NASADIT="${{ inputs.nasadit_verzi }}"
-          TEST_MOD="${{ inputs.test_mod }}"
-          REF_NAME="${{ github.ref_name }}"
-          TEST_CISLO="${{ inputs.test_cislo }}"
-
-          ssh amcr@${{ secrets.DEPLOYMENT_SERVER_DEV }} bash << 'EOF'
-            set -e
-
-            cd '"${{ env.server_deploy_root }}"'
-
-            chmod +x '"${{ env.dep_script }}"'
-            chmod +x '"${{ env.test_script }}"'
-
-            # Deployment
-            if [ "'"$NASADIT"'" = "true" ]; then
-              echo "Nasazuji verzi: '"$REF_NAME"'"
-              # ./'"${{ env.dep_script }}"' '"${{ env.server_deploy_root }}"' '"$REF_NAME"'
-            fi
-
-            # Testování
-            echo "Spouštím testy v režimu: '"$TEST_MOD"'"
-
-            case "'"$TEST_MOD"'" in
-              vsechny)
-                echo "Testuji vše"
-                # ./'"${{ env.test_script }}"'
-                ;;
-              neuspesne)
-                echo "Testuji pouze neúspěšné"
-                # ./'"${{ env.test_script }}"' -f
-                ;;
-              konkretni)
-                echo "Testuji test č. '"$TEST_CISLO"'"
-                # ./'"${{ env.test_script }}"' -t '"$TEST_CISLO"'
-                ;;
-              *)
-                echo "::error::Neznámý režim testu: '"$TEST_MOD"'"
-                exit 1
-                ;;
-            esac
+          echo "Spouštím testy v režimu: $TEST_MOD"
+          case "$TEST_MOD" in
+          vsechny)
+          echo "Testuji vše"
+          ./${{ env.test_script }}
+          ;;
+          neuspesne)
+          echo "Testuji pouze neúspěšné"
+          ./${{ env.test_script }} -f
+          ;;
+          konkretni)
+          echo "Testuji test č. ${{ inputs.test_cislo }}"
+          ./${{ env.test_script }} -t ${{ inputs.test_cislo }}
+          ;;
+          *)
+          echo "::error::Neznámý režim testu: $TEST_MOD"
+          exit 1
+          ;;
+          esac
+          AOF
           EOF
 
       - name: Stáhnout a zobrazit výsledky testů
